INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(1, 'Andres', 'Guzman', 'andres.guzman@lab.com', '2017-08-28','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(2, 'Abel', 'Ramos', 'abel.ramos@lab.com', '2018-11-28','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(3, 'Jisashi', 'Nakamura', 'j.nakamura@lab.com', '2018-05-11','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(4, 'Mari', 'Lopez', 'm.lopez@lab.com', '2018-02-15','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(5, 'Jose', 'Lopez', 'j.lopez@lab.com', '2018-04-10','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(6, 'Andres', 'Guzman 2', 'andres.guzman@lab.com', '2017-08-28','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(7, 'Abel', 'Cruz', 'abel.cruz@lab.com', '2017-11-18','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(8, 'Jaime', 'Nakamura', 'j.nakamura2@lab.com', '2016-03-11','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(9, 'Martha', 'Ruiz', 'm.ruiz@lab.com', '2013-12-15','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(10, 'Jose Ma', 'Lopez', 'j.malopez@lab.com', '2018-01-11','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(11, 'Andres', 'Guzman', 'andres.guzman@lab.com', '2017-08-28','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(12, 'Abel', 'Ramos', 'abel.ramos@lab.com', '2018-11-28','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(13, 'Jisashi', 'Nakamura', 'j.nakamura@lab.com', '2018-05-11','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(14, 'Mari', 'Lopez', 'm.lopez@lab.com', '2018-02-15','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(15, 'Jose', 'Lopez', 'j.lopez@lab.com', '2018-04-10','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(16, 'Andres', 'Guzman 2', 'andres.guzman@lab.com', '2017-08-28','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(17, 'Abel', 'Cruz', 'abel.cruz@lab.com', '2017-11-18','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(18, 'Jaime', 'Nakamura', 'j.nakamura2@lab.com', '2016-03-11','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(19, 'Martha', 'Ruiz', 'm.ruiz@lab.com', '2013-12-15','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(20, 'Jose Ma', 'Lopez', 'j.malopez@lab.com', '2018-01-11','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(21, 'Andres', 'Guzman', 'andres.guzman@lab.com', '2017-08-28','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(22, 'Abel', 'Ramos', 'abel.ramos@lab.com', '2018-11-28','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(23, 'Jisashi', 'Nakamura', 'j.nakamura@lab.com', '2018-05-11','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(24, 'Mari', 'Lopez', 'm.lopez@lab.com', '2018-02-15','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(25, 'Jose', 'Lopez', 'j.lopez@lab.com', '2018-04-10','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(26, 'Andres', 'Guzman 2', 'andres.guzman@lab.com', '2017-08-28','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(27, 'Abel', 'Cruz', 'abel.cruz@lab.com', '2017-11-18','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(28, 'Jaime', 'Nakamura', 'j.nakamura2@lab.com', '2016-03-11','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(29, 'Martha', 'Ruiz', 'm.ruiz@lab.com', '2013-12-15','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(30, 'Jose Ma', 'Lopez', 'j.malopez@lab.com', '2018-01-11','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(31, 'Andres', 'Guzman', 'andres.guzman@lab.com', '2017-08-28','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(32, 'Abel', 'Ramos', 'abel.ramos@lab.com', '2018-11-28','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(33, 'Jisashi', 'Nakamura', 'j.nakamura@lab.com', '2018-05-11','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(34, 'Mari', 'Lopez', 'm.lopez@lab.com', '2018-02-15','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(35, 'Jose', 'Lopez', 'j.lopez@lab.com', '2018-04-10','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(36, 'Andres', 'Guzman 2', 'andres.guzman@lab.com', '2017-08-28','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(37, 'Abel', 'Cruz', 'abel.cruz@lab.com', '2017-11-18','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(38, 'Jaime', 'Nakamura', 'j.nakamura2@lab.com', '2016-03-11','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(39, 'Martha', 'Ruiz', 'm.ruiz@lab.com', '2013-12-15','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(40, 'Jose Ma', 'Lopez', 'j.malopez@lab.com', '2018-01-11','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(41, 'Andres', 'Guzman', 'andres.guzman@lab.com', '2017-08-28','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(42, 'Abel', 'Ramos', 'abel.ramos@lab.com', '2018-11-28','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(43, 'Jisashi', 'Nakamura', 'j.nakamura@lab.com', '2018-05-11','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(44, 'Mari', 'Lopez', 'm.lopez@lab.com', '2018-02-15','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(45, 'Jose', 'Lopez', 'j.lopez@lab.com', '2018-04-10','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(46, 'Andres', 'Guzman 2', 'andres.guzman@lab.com', '2017-08-28','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(47, 'Abel', 'Cruz', 'abel.cruz@lab.com', '2017-11-18','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(48, 'Jaime', 'Nakamura', 'j.nakamura2@lab.com', '2016-03-11','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(49, 'Martha', 'Ruiz', 'm.ruiz@lab.com', '2013-12-15','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(50, 'Jose Ma', 'Lopez', 'j.malopez@lab.com', '2018-01-11','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(51, 'Andres', 'Guzman', 'andres.guzman@lab.com', '2017-08-28','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(52, 'Abel', 'Ramos', 'abel.ramos@lab.com', '2018-11-28','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(53, 'Jisashi', 'Nakamura', 'j.nakamura@lab.com', '2018-05-11','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(54, 'Mari', 'Lopez', 'm.lopez@lab.com', '2018-02-15','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(55, 'Jose', 'Lopez', 'j.lopez@lab.com', '2018-04-10','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(56, 'Andres', 'Guzman 2', 'andres.guzman@lab.com', '2017-08-28','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(57, 'Abel', 'Cruz', 'abel.cruz@lab.com', '2017-11-18','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(58, 'Jaime', 'Nakamura', 'j.nakamura2@lab.com', '2016-03-11','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(59, 'Martha', 'Ruiz', 'm.ruiz@lab.com', '2013-12-15','');
INSERT INTO clientes (id, nombre, apellidos, email, create_at, foto) VALUES(600, 'Jose Ma', 'Lopez', 'j.malopez@lab.com', '2018-01-11','');